name: hotspot
description: Easy product tours
version: 0.0.2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null
