name: hotspot
description: Simple tours, coachmarks, and tutorials
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null
